export const INTERNAL_LINK_GRAPH = {
  '/': [],
  '/services/mechanical-systems/': [
    { name: 'Jaw station integration', url: '/jaw-station-integration/' },
    { name: 'Crusher station fabrication', url: '/crusher-station-fabrication/' },
    { name: 'Cone crusher structural mounting', url: '/cone-crusher-structural-mounting/' },
    { name: 'Vibrating screen fabrication', url: '/vibrating-screen-fabrication/' },
    { name: 'Mining conveyor system design', url: '/mining-conveyor-system-design/' },
    { name: 'Wear protection systems', url: '/wear-protection-systems/' },
    { name: 'Crusher discharge chute', url: '/crusher-discharge-chute-engineering/' },
  ],
  '/jaw-station-integration/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Independent system integrator', url: '/independent-system-integrator/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/crusher-station-fabrication/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Mobile crushing integration', url: '/mobile-crushing-plant-integration/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/cone-crusher-structural-mounting/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Independent system integrator', url: '/independent-system-integrator/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/vibrating-screen-fabrication/': [
    { name: 'Vietnam quarry integration', url: '/vietnam-quarry-plant-integration/' },
    { name: 'Screening plant engineering', url: '/screening-plant-engineering-company/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/mining-conveyor-system-design/': [
    { name: 'Indonesia mining conveyors', url: '/indonesia-mining-conveyor-integration/' },
    { name: 'Mobile crushing integration', url: '/mobile-crushing-plant-integration/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/wear-protection-systems/': [
    { name: 'South Africa crushing plant', url: '/south-africa-crushing-plant-engineering/' },
    { name: 'Mobile crushing integration', url: '/mobile-crushing-plant-integration/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/crusher-discharge-chute-engineering/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Mobile crushing integration', url: '/mobile-crushing-plant-integration/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/services/electrical-automation/': [
    { name: 'Plant electrical integration', url: '/crushing-plant-electrical-integration/' },
    { name: 'MCC panel fabrication', url: '/mcc-panel-fabrication-mining/' },
    { name: 'PLC programming quarry plants', url: '/plc-programming-quarry-plants/' },
    { name: 'Industrial control panels', url: '/industrial-control-panels-mining/' },
    { name: 'VFD systems conveyors', url: '/vfd-systems-conveyors/' },
  ],
  '/crushing-plant-electrical-integration/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Commissioning Middle East', url: '/crushing-plant-commissioning-middle-east/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/mcc-panel-fabrication-mining/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Commissioning Middle East', url: '/crushing-plant-commissioning-middle-east/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/plc-programming-quarry-plants/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Commissioning Middle East', url: '/crushing-plant-commissioning-middle-east/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/industrial-control-panels-mining/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Commissioning Middle East', url: '/crushing-plant-commissioning-middle-east/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/vfd-systems-conveyors/': [
    { name: 'Indonesia mining conveyors', url: '/indonesia-mining-conveyor-integration/' },
    { name: 'Screening plant engineering', url: '/screening-plant-engineering-company/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/industries/': [
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Vietnam quarry integration', url: '/vietnam-quarry-plant-integration/' },
    { name: 'Indonesia mining conveyors', url: '/indonesia-mining-conveyor-integration/' },
    { name: 'South Africa crushing plant', url: '/south-africa-crushing-plant-engineering/' },
    { name: 'Bulk material handling', url: '/bulk-material-handling-system-integrator/' },
  ],
  '/gcc-hard-rock-processing/': [
    { name: 'Jaw station integration', url: '/jaw-station-integration/' },
    { name: 'Crusher station fabrication', url: '/crusher-station-fabrication/' },
    { name: 'Cone crusher structural mounting', url: '/cone-crusher-structural-mounting/' },
    { name: 'Vibrating screen fabrication', url: '/vibrating-screen-fabrication/' },
    { name: 'Mining conveyor system design', url: '/mining-conveyor-system-design/' },
    { name: 'Wear protection systems', url: '/wear-protection-systems/' },
    { name: 'Crusher discharge chute', url: '/crusher-discharge-chute-engineering/' },
    { name: 'Plant electrical integration', url: '/crushing-plant-electrical-integration/' },
    { name: 'MCC panel fabrication', url: '/mcc-panel-fabrication-mining/' },
    { name: 'PLC programming quarry plants', url: '/plc-programming-quarry-plants/' },
    { name: 'Industrial control panels', url: '/industrial-control-panels-mining/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/vietnam-quarry-plant-integration/': [
    { name: 'Vibrating screen fabrication', url: '/vibrating-screen-fabrication/' },
    { name: 'Mining conveyor system design', url: '/mining-conveyor-system-design/' },
    { name: 'Bulk material handling', url: '/bulk-material-handling-system-integrator/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/indonesia-mining-conveyor-integration/': [
    { name: 'Mining conveyor system design', url: '/mining-conveyor-system-design/' },
    { name: 'VFD systems conveyors', url: '/vfd-systems-conveyors/' },
    { name: 'Bulk material handling', url: '/bulk-material-handling-system-integrator/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/south-africa-crushing-plant-engineering/': [
    { name: 'Crusher station fabrication', url: '/crusher-station-fabrication/' },
    { name: 'Wear protection systems', url: '/wear-protection-systems/' },
    { name: 'MCC panel fabrication', url: '/mcc-panel-fabrication-mining/' },
    { name: 'Plant electrical integration', url: '/crushing-plant-electrical-integration/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/bulk-material-handling-system-integrator/': [
    { name: 'Mining conveyor system design', url: '/mining-conveyor-system-design/' },
    { name: 'Crusher discharge chute', url: '/crusher-discharge-chute-engineering/' },
    { name: 'VFD systems conveyors', url: '/vfd-systems-conveyors/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/approach/': [
    { name: 'Independent system integrator', url: '/independent-system-integrator/' },
    { name: 'Mobile crushing integration', url: '/mobile-crushing-plant-integration/' },
    { name: 'Commissioning Middle East', url: '/crushing-plant-commissioning-middle-east/' },
    { name: 'Screening plant engineering', url: '/screening-plant-engineering-company/' },
  ],
  '/independent-system-integrator/': [
    { name: 'Jaw station integration', url: '/jaw-station-integration/' },
    { name: 'Cone crusher structural mounting', url: '/cone-crusher-structural-mounting/' },
    { name: 'Mining conveyor system design', url: '/mining-conveyor-system-design/' },
    { name: 'MCC panel fabrication', url: '/mcc-panel-fabrication-mining/' },
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/mobile-crushing-plant-integration/': [
    { name: 'Crusher station fabrication', url: '/crusher-station-fabrication/' },
    { name: 'Wear protection systems', url: '/wear-protection-systems/' },
    { name: 'VFD systems conveyors', url: '/vfd-systems-conveyors/' },
    { name: 'Crusher discharge chute', url: '/crusher-discharge-chute-engineering/' },
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/crushing-plant-commissioning-middle-east/': [
    { name: 'Plant electrical integration', url: '/crushing-plant-electrical-integration/' },
    { name: 'PLC programming quarry plants', url: '/plc-programming-quarry-plants/' },
    { name: 'Industrial control panels', url: '/industrial-control-panels-mining/' },
    { name: 'GCC hard rock processing', url: '/gcc-hard-rock-processing/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/screening-plant-engineering-company/': [
    { name: 'Vibrating screen fabrication', url: '/vibrating-screen-fabrication/' },
    { name: 'Wear protection systems', url: '/wear-protection-systems/' },
    { name: 'VFD systems conveyors', url: '/vfd-systems-conveyors/' },
    { name: 'Bulk material handling', url: '/bulk-material-handling-system-integrator/' },
    { name: 'Vietnam quarry integration', url: '/vietnam-quarry-plant-integration/' },
    { name: 'Why Maketronics', url: '/why-maketronics/' },
  ],
  '/why-maketronics/': [
    { name: 'Mechanical hub', url: '/services/mechanical-systems/' },
    { name: 'Electrical hub', url: '/services/electrical-automation/' },
    { name: 'Industries hub', url: '/industries/' },
    { name: 'Approach hub', url: '/approach/' },
  ],
};

export const PAGE_TITLES = {
  '/': 'Homepage',
  '/services/mechanical-systems/': 'Mechanical hub',
  '/jaw-station-integration/': 'Jaw station integration',
  '/crusher-station-fabrication/': 'Crusher station fabrication',
  '/cone-crusher-structural-mounting/': 'Cone crusher structural mounting',
  '/vibrating-screen-fabrication/': 'Vibrating screen fabrication',
  '/mining-conveyor-system-design/': 'Mining conveyor system design',
  '/wear-protection-systems/': 'Wear protection systems',
  '/crusher-discharge-chute-engineering/': 'Crusher discharge chute',
  '/services/electrical-automation/': 'Electrical hub',
  '/crushing-plant-electrical-integration/': 'Plant electrical integration',
  '/mcc-panel-fabrication-mining/': 'MCC panel fabrication',
  '/plc-programming-quarry-plants/': 'PLC programming quarry plants',
  '/industrial-control-panels-mining/': 'Industrial control panels',
  '/vfd-systems-conveyors/': 'VFD systems conveyors',
  '/industries/': 'Industries hub',
  '/gcc-hard-rock-processing/': 'GCC hard rock processing',
  '/vietnam-quarry-plant-integration/': 'Vietnam quarry integration',
  '/indonesia-mining-conveyor-integration/': 'Indonesia mining conveyors',
  '/south-africa-crushing-plant-engineering/': 'South Africa crushing plant',
  '/bulk-material-handling-system-integrator/': 'Bulk material handling',
  '/approach/': 'Approach hub',
  '/independent-system-integrator/': 'Independent system integrator',
  '/mobile-crushing-plant-integration/': 'Mobile crushing integration',
  '/crushing-plant-commissioning-middle-east/': 'Commissioning Middle East',
  '/screening-plant-engineering-company/': 'Screening plant engineering',
  '/why-maketronics/': 'Why Maketronics',
};

export const normalizePath = (path) => (path.endsWith('/') && path.length > 1 ? path.slice(0, -1) : path);

export const PATH_FOLDER = {
  '/': 'Home',
  '/services/mechanical-systems/': 'Mechanical',
  '/jaw-station-integration/': 'Mechanical',
  '/crusher-station-fabrication/': 'Mechanical',
  '/cone-crusher-structural-mounting/': 'Mechanical',
  '/vibrating-screen-fabrication/': 'Mechanical',
  '/mining-conveyor-system-design/': 'Mechanical',
  '/wear-protection-systems/': 'Mechanical',
  '/crusher-discharge-chute-engineering/': 'Mechanical',
  '/services/electrical-automation/': 'Electrical',
  '/crushing-plant-electrical-integration/': 'Electrical',
  '/mcc-panel-fabrication-mining/': 'Electrical',
  '/plc-programming-quarry-plants/': 'Electrical',
  '/industrial-control-panels-mining/': 'Electrical',
  '/vfd-systems-conveyors/': 'Electrical',
  '/industries/': 'Industry',
  '/gcc-hard-rock-processing/': 'Industry',
  '/vietnam-quarry-plant-integration/': 'Industry',
  '/indonesia-mining-conveyor-integration/': 'Industry',
  '/south-africa-crushing-plant-engineering/': 'Industry',
  '/bulk-material-handling-system-integrator/': 'Industry',
  '/approach/': 'Approach',
  '/independent-system-integrator/': 'Approach',
  '/mobile-crushing-plant-integration/': 'Approach',
  '/crushing-plant-commissioning-middle-east/': 'Approach',
  '/screening-plant-engineering-company/': 'Approach',
  '/why-maketronics/': 'Why Us',
};

export const getLinksForPath = (path) => {
  const current = normalizePath(path);
  const entry = Object.entries(INTERNAL_LINK_GRAPH).find(([source]) => normalizePath(source) === current);
  if (!entry) return [];
  return entry[1];
};
